name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration=production --base-href=/face-detection-app/

      - name: Copy index.html to 404.html
        run: cp dist/face-detection-app/browser/index.html dist/face-detection-app/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/face-detection-app/browser
          branch: gh-pages
          clean: true
